Product.create(title: 'Nike Headband', price: 30, inventory_count: 10)
Product.create(title: 'Nike Arm Sleeve', price: 35, inventory_count: 10)
Product.create(title: 'Nike Basketball', price: 60, inventory_count: 10)
Product.create(title: 'Nike Compression Tights', price: 50, inventory_count: 10)
Product.create(title: 'Nike Joggers', price: 30, inventory_count: 10)
Product.create(title: 'Nike Tee Shirt', price: 30, inventory_count: 10)
Product.create(title: 'Nike Facemask', price: 30, inventory_count: 10)
Product.create(title: 'Nike Bag', price: 100, inventory_count: 10)
Product.create(title: 'Lebrons 16', price: 300, inventory_count: 10)
Product.create(title: 'Kyrie 3', price: 220, inventory_count: 10)
Product.create(title: 'Kyrie 2', price: 220, inventory_count: 0)
Product.create(title: 'Kyrie 1', price: 220, inventory_count: 0)
